### PR TITLE
V2.7.8 rc

### LINKED ISSUE #412: timeout cli is missing on MacOS Catalina causing `Vault status: unreachable`
I'm seeing the following error
```
 VALUE ⮀ run_output = ''
         # in Genesis::mkdir_or_fail [/var/folders/67/pp789x9n1979f0khpgwwrx5w0000gn/T/938554116-salvation-home/.geese/lib/Genesis.pm:L609]
 VALUE ⮀ run_output = '{
           "name": "tempered-refuge",
           "url": "http://127.0.0.1:8208",
           "verify": true,
           "strongbox": false
         }'
         # in Genesis::Vault::default [/var/folders/67/pp789x9n1979f0khpgwwrx5w0000gn/T/938554116-salvation-home/.geese/lib/Genesis/Vault.pm:L182]
 VALUE ⮀ run_output = '[{"name":"tempered-refuge","url":"http://127.0.0.1:8208","verify":true}]'
         # in Genesis::Vault::find [/var/folders/67/pp789x9n1979f0khpgwwrx5w0000gn/T/938554116-salvation-home/.geese/lib/Genesis/Vault.pm:L161]
Verifying availability of selected vault... VALUE ⮀ run_output = '/bin/bash: timeout: command not found'
         # in Genesis::tcp_listening [/var/folders/67/pp789x9n1979f0khpgwwrx5w0000gn/T/938554116-salvation-home/.geese/lib/Genesis.pm:L720]
unreachable
 DEBUG ⮀ Vault status: unreachable
 DEBUG ⮀ removing incomplete Genesis deployments repository at ./deployments due to failed creation
```

Could workaround it by: `ln -s /usr/local/bin/gtimeout /usr/local/bin/timeout` after install `coreutils` via homebrew.

### LINKED ISSUE #413: Genesis rotate-secrets on a bosh deployment, not properly handling re-entry of iaas credential block
Genesis version: 2.7.7
Bosh kit version: 1.10.2

Running `genesis rotate-secrets` on a bosh deployment in gcp I once again get prompted for the json key for the service account. After pasting it appears genesis rotate-secrets does not like multi-line credentials in the current state.

### LINKED ISSUE #414: rotate-secrets --probematic should be --problematic
I don't really want to activate the probe-matic

### PR DESCRIPTION
**Pull request by dennisjbell**
# Improvements

* Now supports extraction of bosh variables and credhub secrets into exodus
  data for cross-kit integration and addon support.

* When testing availability of the vault, it specifies the alias and url of
  the vault instead of specifying "selected vault"

# Bug Fixes

* Universal support for timeout detection when attempting to connect to remote
  BOSH and Vault, with better feedback in case of timeout (Fixes #412)

* Adds support for multiline provided secrets rotation and addition (Fixes #413)

* Fix typo in rotate-secrets help (Fixes #414)

* Deployments using legacy mode for secrets providers now get the vault
  connection validated prior to using it

* Fixed bug where non-standard secrets mount would report the vault was
  uninitialized.

### CODE REVIEW

File: lib/Genesis/Env.pm [hunk 1]
```diff
@@ -943,16 +1028,23 @@ sub deploy {
...
 	my $exodus = $self->exodus;
+
 	$exodus->{manifest_sha1} = digest_file_hex($manifest_path, 'SHA-1');
 	$exodus->{bosh} = $self->bosh_target || "(none)";
 	debug("setting exodus data in the Vault, for use later by other deployments");
 	$ok = $self->vault->query(
-		{ onfailure => "Successfully deployed, but could not save $self->{name} metadata to the Vault" },
+		{ onfailure => "#R{Failed to export $self->{name} metadata.}\n".
+		               "Deployment was still successful, but metadata used by addons and other kits is outdated.\n".
+		               "This may be resolved by deploying again, or it maybe a permissions issue while trying to\n".
```
Comment (thomasmitchell) [inline lib/Genesis/Env.pm:1040]:
```suggestion
		               "This may be resolved by deploying again, or it may be a permissions issue while trying to\n".
```
